### ISSUE TITLE
Question about requirements

### ISSUE THREAD

**Issue by ufukefe** [ignacio-rocco/ncnet#9]
Hi Ignacio, thank you for your good work. I am also interested in your new paper Sparse-NCNet but I want to work on NCNet first.
I created an environment using anaconda, python=3.6 and torchvision=0.3.0 with CUDA 9.0

When I run 
`python eval_pf_pascal.py --checkpoint trained_models/ncnet_pfpascal.pth.tar`

I got

```
NCNet evaluation script - PF Pascal dataset
Creating CNN model...
Loading checkpoint...
Using checkpoint parameters: 
  ncons_channels: [16, 16, 1]
  ncons_kernel_sizes: [5, 5, 5]
Traceback (most recent call last):
  File "eval_pf_pascal.py", line 37, in <module>
    checkpoint=args.checkpoint)
  File "/home/ufuk/Desktop/ncnet-master/lib/model.py", line 239, in __init__
    channels=ncons_channels)
  File "/home/ufuk/Desktop/ncnet-master/lib/model.py", line 137, in __init__
    nn_modules.append(Conv4d(in_channels=ch_in,out_channels=ch_out,kernel_size=k_size,bias=True))
  File "/home/ufuk/Desktop/ncnet-master/lib/conv4d.py", line 71, in __init__
    False, _quadruple(0), groups, bias)  
TypeError: __init__() missing 1 required positional argument: 'padding_mode'
```
What would be the reason for this, do you have any idea. Did you use the same libraries?

Thank you :) 
Ufuk

**Comment by ufukefe** [comment]
I have solved the problem, here is the working dependencies for me (for ones who has CUDA 9.0);

Create and activate anaconda environement;

`conda create -n ncnet python=3.6
conda activate ncnet`

Then install pytorch 0.4.1 and torchvision

`conda install pytorch=0.4.1 cuda90 -c pytorch`
`conda install torchvision`

After these install scikit-image

`conda install scikit-image`

At the end, install pandas version 0.25.3 (with latest version of pandas=1.1.0 I got an error, `AttributeError: 'Series' object has no attribute 'as_matrix')

`conda install pandas==0.25.3`


Here is the list of all packages of my environment;

Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.6.24                     0  
certifi                   2020.6.20                py36_0  
cffi                      1.14.1           py36he30daa8_0  
cloudpickle               1.5.0                      py_0  
cuda90                    1.0                  h6433d27_0    pytorch
cycler                    0.10.0                   py36_0  
cytoolz                   0.10.1           py36h7b6447c_0  
dask-core                 2.22.0                     py_0  
dbus                      1.13.16              hb2f20db_0  
decorator                 4.4.2                      py_0  
expat                     2.2.9                he6710b0_2  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.2               h5ab3b9f_0  
glib                      2.65.0               h3eb4bd4_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
icu                       58.2                 he6710b0_3  
imageio                   2.9.0                      py_0  
intel-openmp              2020.1                      217  
jpeg                      9b                   h024ee3a_2  
kiwisolver                1.2.0            py36hfd86e86_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               he19cac6_1  
lz4-c                     1.9.2                he6710b0_1  
matplotlib                3.2.2                         0  
matplotlib-base           3.2.2            py36hef1b27d_0  
mkl                       2020.1                      217  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.1.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
networkx                  2.4                        py_1  
ninja                     1.10.0           py36hfd86e86_0  
numpy                     1.19.1           py36hbc911f0_0  
numpy-base                1.19.1           py36hfa32c7d_0  
olefile                   0.46                     py36_0  
openssl                   1.1.1g               h7b6447c_0  
pandas                    0.25.3           py36hb3f55d8_0    conda-forge
pcre                      8.44                 he6710b0_0  
pillow                    7.2.0            py36hb39fc2d_0  
pip                       20.2.1                   py36_0  
pycparser                 2.20                       py_2  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py36h05f1152_2  
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                      py_0  
pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py36h7b6447c_0  
pyyaml                    5.3.1            py36h7b6447c_1  
qt                        5.9.7                h5867ecd_1  
readline                  8.0                  h7b6447c_0  
scikit-image              0.16.2           py36h0573a6f_0  
scipy                     1.5.0            py36h0b6359f_0  
setuptools                49.2.1                   py36_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.15.0                     py_0  
sqlite                    3.32.3               h62c20be_0  
tk                        8.6.10               hbc83047_0  
toolz                     0.10.0                     py_0  
torchvision               0.2.1                    py36_0  
tornado                   6.0.4            py36h7b6447c_1  
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by Acmenwangtuo** [comment]
I have the question that still have the problem __init__() missing 1 required positional argument: 'padding_mode'
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
absl-py                   0.9.0                    pypi_0    pypi
addict                    2.3.0                    pypi_0    pypi
albumentations            0.4.6                      py_0    conda-forge
astroid                   2.4.2                    pypi_0    pypi
attrs                     19.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      2.17                   openblas    conda-forge
bleach                    3.1.5                    pypi_0    pypi
blosc                     1.19.0               he1b5a44_0    conda-forge
brotli                    1.0.7             he1b5a44_1004    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20        py36h9f0ad1d_0    conda-forge
cffi                      1.14.6           py36hc120d54_0    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
chardet                   3.0.4                    pypi_0    pypi
charls                    2.1.0                he1b5a44_2    conda-forge
cloudpickle               1.5.0                      py_0    conda-forge
cuda90                    1.0                  h6433d27_0    pytorch
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py36h516909a_0    conda-forge
dask-core                 2.21.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype                  2.10.2               he06d7ca_0    conda-forge
future                    0.18.2                   pypi_0    pypi
geos                      3.8.1                he1b5a44_0    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
google-auth               1.18.0                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
grpcio                    1.30.0                   pypi_0    pypi
hdf5                      1.10.2               hc401514_3    conda-forge
idna                      2.10                     pypi_0    pypi
imagecodecs               2020.5.30        py36hc75b63b_1    conda-forge
imageio                   2.9.0                      py_0    conda-forge
imgaug                    0.4.0                      py_1    conda-forge
importlib-metadata        1.7.0                    pypi_0    pypi
inplace-abn               1.0.12                   pypi_0    pypi
ipykernel                 5.3.4                    pypi_0    pypi
ipython                   7.16.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.5.1                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jedi                      0.17.2                   pypi_0    pypi
jinja2                    2.11.2                   pypi_0    pypi
joblib                    0.16.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jpeg                      9d                   h516909a_0    conda-forge
jsonschema                3.2.0                    pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            6.1.6                    pypi_0    pypi
jupyter-console           6.1.0                    pypi_0    pypi
jupyter-core              4.6.3                    pypi_0    pypi
jxrlib                    1.1                  h516909a_2    conda-forge
kiwisolver                1.2.0            py36hdb11119_0    conda-forge
lazy-object-proxy         1.4.3                    pypi_0    pypi
lcms2                     2.11                 hbd6801e_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libaec                    1.0.4                he1b5a44_1    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libedit                   3.1.20191231         h7b6447c_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h24d8f2e_16    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
liblapacke                3.8.0               17_openblas    conda-forge
libopenblas               0.3.10          pthreads_hb3c22a3_3    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                hc7e4089_6    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libzopfli                 1.0.3                he1b5a44_0    conda-forge
llvm-openmp               10.0.1               hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
markdown                  3.2.2                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.2.2                    pypi_0    pypi
matplotlib-base           3.3.0            py36h5ffbc53_1    conda-forge
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2020.2                      256    http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mmcv-full                 1.1.2                    pypi_0    pypi
mmsegmentation            0.6.0                     dev_0    <develop>
nbconvert                 5.6.1                    pypi_0    pypi
nbformat                  5.0.7                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1    defaults
networkx                  2.4                        py_1    conda-forge
ninja                     1.7.2                         0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
notebook                  6.0.3                    pypi_0    pypi
numpy                     1.19.0           py36h7314795_0    conda-forge
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
opencv                    3.4.1            py36h6fd60c2_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
opencv-python             4.3.0.36                 pypi_0    pypi
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1g               h516909a_1    conda-forge
packaging                 20.4                     pypi_0    pypi
pandas                    0.25.3                   pypi_0    pypi
pandocfilters             1.4.2                    pypi_0    pypi
parso                     0.7.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0            py36h8328e55_1    conda-forge
pip                       20.1.1                   py36_1    defaults
pretty-table-printer      0.5.0                    pypi_0    pypi
prettytable               0.7.2                    pypi_0    pypi
prometheus-client         0.8.0                    pypi_0    pypi
prompt-toolkit            3.0.5                    pypi_0    pypi
protobuf                  3.12.2                   pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.18                     py36_0    https://mirrors.ustc.edu.cn/anaconda/pkgs/free
pydensecrf                1.0rc3                   pypi_0    pypi
pygments                  2.6.1                    pypi_0    pypi
pylint                    2.5.3                    pypi_0    pypi
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.16.0                   pypi_0    pypi
python                    3.6.10               h7579374_2    defaults
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytorch                   0.4.1           py36_py35_py27__9.0.176_7.1.2_2    pytorch
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.1.1            py36h785e9b2_1    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
qtconsole                 4.7.5                    pypi_0    pypi
qtpy                      1.9.0                    pypi_0    pypi
readline                  8.0                  h7b6447c_0    defaults
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scikit-image              0.17.2           py36h830a2c2_1    conda-forge
scikit-learn              0.23.1           py36h7ea95a0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.2.1                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                47.3.1                   py36_0    defaults
shapely                   1.7.0            py36h3d6ee9d_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sqlite                    3.32.3               h62c20be_0    defaults
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorboardx              2.1                      pypi_0    pypi
terminado                 0.8.3                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tifffile                  2020.7.4                   py_0    conda-forge
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.1                   pypi_0    pypi
toolz                     0.10.0                     py_0    conda-forge
torchvision               0.2.1                    pypi_0    pypi
tornado                   6.0.4            py36h8c4c3a4_1    conda-forge
tqdm                      4.47.0                   pypi_0    pypi
traitlets                 4.3.3                    pypi_0    pypi
ttach                     0.0.3                    pypi_0    pypi
typed-ast                 1.4.1                    pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.34.2                   py36_0    defaults
widgetsnbextension        3.5.1                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h516909a_0    conda-forge
yapf                      0.30.0                   pypi_0    pypi
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h6597ccf_1    conda-forge
